services:
  frontend:
    build:
      context: frontend
    tty: true
    volumes:
      - ./frontend/src/app:/app
    environment:
      - WATCHPACK_POLLING=value
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: husen_api
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=fusen_db
    volumes:
      - ./backend:/usr/src/app
    networks:
      - api_network

  db:
    image: mysql:8.0
    container_name: fusen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fusen_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_network

volumes:
  db_data:

networks:
  api_network:
